### ISSUE TITLE
分类的问题？

### ISSUE THREAD

**Issue by codingsnippets** [LiuGuiLinAndroid/Coding-Developer-Book#1]
https://github.com/LiuGuiLinAndroid/Coding-Developer-Book/blob/master/%E4%BA%A7%E5%93%81%E7%BB%8F%E7%90%86/UNIX%E7%8E%AF%E5%A2%83%E9%AB%98%E7%BA%A7%E7%BC%96%E7%A8%8B_%E7%AC%AC%E4%BA%8C%E7%89%88%E4%B8%AD%E6%96%87.pdf

UNIX环境高级编程跟产品经理关系不大吧？该是Linux？

**Comment by LiuGuiLinAndroid** [comment]
分类可能有些有点小疏忽，非常感谢，我会修改的
